name: ${plugin.name}
version: ${plugin.version}
main: ${plugin.main}
api-version: 1.20
description: ${plugin.description}
commands:
  example:
    description: Comando de exemplo básico
    usage: /example [help|info]
    aliases: [ex]
  advanced:
    description: Comando de exemplo avançado com subcomandos
    usage: /advanced [help|menu|info|set|get]
    aliases: [adv]
